### ISSUE TITLE
Help for localisation

### ISSUE THREAD

**Issue by Happyclem** [jakeledoux/fsim2#10]
Hello Jake,

I was cleaning my internet footprint when I found my old itch.io account.
I made my friend play fallout simulator for a bit saying I helped for this game translation.
A couple minutes later he send me a link to your github and this project.

Not an issue here, just saying hello !

If by any chance you are still invested in this game, i'll gladly take a lot at how I could, other than just languages !

Lot of loves !

Edit : There is some errors in what I did in the original game, i'm so sorry x) Can adjust that now.

**Comment by jakeledoux** [comment]
Hey dude! Glad to hear from you :)

This project is pretty old and I don't plan on reviving it unfortunately (busy with work these days!) If I ever end up making a sequel though I'll get in touch with you.

Many thanks for your help in the past! Cheers.
